Feat fix table 28
zyfra/Prizm pull request #113
Opened 2023-03-29 11:10 UTC by ZurabDev

## Features
- fix(components/table): pass correct context to row [110](https://github.com/zyfra/Prizm/issues/110)

2023-03-30 11:54 UTC, alexhawkins94 submitted a review, later dismissed

2023-03-31 07:47 UTC, alexhawkins94 commented
При изменении масштаба браузера sticky колонки и ряды отображаются некорректно - будто в отрыве от остальной таблицы

![chrome_RaPsePwcox](https://user-images.githubusercontent.com/122870313/229057149-6fe67787-ad22-4d3b-a9aa-4ce48b4ce7ba.png)

![chrome_QoqXityOx2](https://user-images.githubusercontent.com/122870313/229057051-5ff7c445-73eb-4672-93f1-154dbb0654cd.png)

2023-03-31 07:48 UTC, alexhawkins94 requested changes
При изменении масштаба браузера sticky колонки и ряды отображаются некорректно - будто в отрыве от остальной таблицы 

![chrome_RaPsePwcox](https://user-images.githubusercontent.com/122870313/229057959-baf8d159-9a4a-440f-b7d5-068be72f246e.png)

![chrome_QoqXityOx2](https://user-images.githubusercontent.com/122870313/229057895-f19c4f6f-4fc2-433e-9b25-6fc288c4bf97.png)

2023-03-31 07:51 UTC, alexhawkins94 commented
В live demo компонента switcher не требуется ли вынести свойство disabled?

2023-03-31 08:16 UTC, alexhawkins94 commented
Двойная граница в примере preset list компонента inputDateRange
![chrome_272YYbpPUl](https://user-images.githubusercontent.com/122870313/229064878-3e2d2c8d-f78b-4446-b39c-29a48eea4e46.png)

2023-03-31 08:53 UTC, alexhawkins94 commented
В пример со sticky колонками в табличке я бы добавил еще горизонтальный скролл - чтоб наглядно было видно, что колонки sticky

2023-03-31 13:42 UTC, YashaKorolev approved these changes

2023-03-31 14:18 UTC, merged