release 1.0.0-beta.22 stage 1
zyfra/Prizm pull request #2
Opened 2023-01-26 07:32 UTC by ZurabDev

2023-01-26 13:18 UTC, skkonstantin approved these changes

2023-01-26 13:38 UTC, alexhawkins94 requested changes
Поправить выпадающий список выбора кол-ва строк на странице для пагинатора 
16 идёт перед 10
![image](https://user-images.githubusercontent.com/122870313/214849387-56e9cbae-d1b0-4996-9706-6f08b338883e.png)

2023-01-26 14:04 UTC, alexhawkins94 reviewed
В live demo  у пагинатора отображается "пусто".
-Перейти в апи пагинатора
-По умолчанию установлено 16 строк, 10 страница.
-Отображается надпись "пусто" над выбором кол-ва строк на странице
-Переключаюсь на 9 страницу и обратно на 10
Фактический результат: надпись более не отображается.

вопрос - что это? )

![chrome_DIfzWlAq9B](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif)

2023-01-27 05:47 UTC, ZurabDev commented
> 

<img width="511" alt="CleanShot 2023-01-27 at 08 46 35@2x" src="https://user-images.githubusercontent.com/75216044/215018332-93c49ec5-79f7-4e8a-aa4d-7e09dcba3459.png">
готово

2023-01-27 05:49 UTC, ZurabDev commented
> В live demo у пагинатора отображается "пусто". -Перейти в апи пагинатора -По умолчанию установлено 16 строк, 10 страница. -Отображается надпись "пусто" над выбором кол-ва строк на странице -Переключаюсь на 9 страницу и обратно на 10 Фактический результат: надпись более не отображается.
> 
> вопрос - что это? )
> 
> ![chrome_DIfzWlAq9B](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif) [ ![chrome_DIfzWlAq9B](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif) ](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif) [ ](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif)

<img width="459" alt="CleanShot 2023-01-27 at 08 49 24@2x" src="https://user-images.githubusercontent.com/75216044/215018556-c1633d1a-ab62-4346-8bc6-602c6aa1292d.png">

2023-01-27 05:50 UTC, ZurabDev commented
> ![chrome_DIfzWlAq9B](https://user-images.githubusercontent.com/122870313/214855361-e3bcfb95-8136-4c42-8dbf-330a407da1dc.gif)

Готово

2023-01-27 08:45 UTC, alexhawkins94 requested changes
Поправить опечатку в примере у Split Button
![chrome_nScUjV6tCN](https://user-images.githubusercontent.com/122870313/215044765-5017dda7-024e-42cc-bfd3-d4239e0379fc.png)

2023-01-27 08:47 UTC, ZurabDev commented
> Поправить опечатку в примере у Split Button ![chrome_nScUjV6tCN](https://user-images.githubusercontent.com/122870313/215044765-5017dda7-024e-42cc-bfd3-d4239e0379fc.png)

Готово

2023-01-27 10:13 UTC, alexhawkins94 approved these changes

2023-01-27 12:49 UTC, alexhawkins94 approved these changes

2023-02-16 05:08 UTC, closed without merging