added page: SLA - Service Level Agreement
zyfra/Prizm pull request #54
Opened 2023-02-20 09:14 UTC by YashaKorolev

2023-02-20 12:19 UTC, alexhawkins94 approved these changes

2023-03-03 06:01 UTC, ZurabDev requested changes

2023-03-03 06:01 UTC, ZurabDev commented on apps/doc/src/app/about-prizm/contacts/contacts.component.ts
> +export const TABLE_LABEL_TYPES: ITableProduct[] = [
Нужно ли их экспортить? Где они еще используются

2023-03-03 13:28 UTC, ZurabDev approved these changes

2023-03-03 13:43 UTC, merged