Изменение type на button у input-icon-button
zyfra/Prizm pull request #62
Opened 2023-02-27 10:37 UTC by skkonstantin

https://github.com/zyfra/Prizm/issues/60

2023-02-28 07:40 UTC, alexhawkins94 reviewed
devOnly

2023-03-03 05:41 UTC, ZurabDev approved these changes

2023-03-03 05:55 UTC, ZurabDev requested changes

2023-03-03 05:55 UTC, ZurabDev commented on libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
> +
` @Input() 
  @HostBinding('attr.type')
  type: 'button' | 'reset' | 'submit' = 'button';`
  
  Важно оставить возможность пользователю контрировать поведение, примерно так, но надо также добавить в доку

2023-03-03 13:17 UTC, ZurabDev approved these changes

2023-03-03 13:17 UTC, merged